package main

import "errors"

var (
	EBadAddr       = errors.New("illegal block address")
	EBDir          = errors.New("corrupted directory entry")
	EBadEntry      = errors.New("corrupted file entry")
	EBadLabel      = errors.New("corrupted block label")
	EBadMeta       = errors.New("corrupted meta data")
	EBadMode       = errors.New("illegal mode")
	EBadOffset     = errors.New("illegal offset")
	EBadPath       = errors.New("illegal path element")
	EBadRoot       = errors.New("root of file system is corrupted")
	EBadSuper      = errors.New("corrupted super block")
	EBlockTooBig   = errors.New("block too big")
	ECacheFull     = errors.New("no free blocks in memory cache")
	EConvert       = errors.New("protocol botch")
	EExists        = errors.New("file already exists")
	EFsFill        = errors.New("file system is full")
	EIO            = errors.New("i/o error")
	EInUse         = errors.New("file is in use")
	ELabelMismatch = errors.New("block label mismatch")
	ENilBlock      = errors.New("illegal block address")
	ENoDir         = errors.New("directory entry is not allocated")
	ENoFile        = errors.New("file does not exist")
	ENotDir        = errors.New("not a directory")
	ENotEmpty      = errors.New("directory not empty")
	ENotFile       = errors.New("not a file")
	EReadOnly      = errors.New("file is read only")
	ERemoved       = errors.New("file has been removed")
	ENotArchived   = errors.New("file is not archived")
	EResize        = errors.New("only support truncation to zero length")
	ERoot          = errors.New("cannot remove root")
	ESnapOld       = errors.New("snapshot has been deleted")
	ESnapRO        = errors.New("snapshot is read only")
	ETooBig        = errors.New("file too big")
	EVentiIO       = errors.New("venti i/o error")
	EUsage         = errors.New("error parsing command")
)
